# Generated by Django 4.0.2 on 2022-03-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
